// flow-typed signature: 6cf790054caf153f530915ea0e3f18d9
// flow-typed version: <<STUB>>/apollo-upload-client_v^8.1.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-upload-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-upload-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-upload-client/lib/main/index' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/lib/module/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-upload-client/lib/main/index.js' {
  declare module.exports: $Exports<'apollo-upload-client/lib/main/index'>;
}
declare module 'apollo-upload-client/lib/module/index.js' {
  declare module.exports: $Exports<'apollo-upload-client/lib/module/index'>;
}
