// flow-typed signature: 3a6e5d001f26ddb235c61a74aac96758
// flow-typed version: <<STUB>>/apollo-link-log_v1.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-log/lib/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'apollo-link-log/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-log/lib/__tests__/index.test.js' {
  declare module.exports: $Exports<'apollo-link-log/lib/__tests__/index.test'>;
}
declare module 'apollo-link-log/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-log/lib/index'>;
}
