// flow-typed signature: 8d7b2b8df69f538063a0ea6e935e7948
// flow-typed version: <<STUB>>/fkill_v^5.3.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fkill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fkill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fkill/index' {
  declare module.exports: $Exports<'fkill'>;
}
declare module 'fkill/index.js' {
  declare module.exports: $Exports<'fkill'>;
}
