// flow-typed signature: 3e6119c886cffce041f648defe4b649f
// flow-typed version: <<STUB>>/googleapis_v^32.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'googleapis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'googleapis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'googleapis/build/src/apis/abusiveexperiencereport/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/abusiveexperiencereport/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/acceleratedmobilepageurl/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/acceleratedmobilepageurl/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer/v1.2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer/v1.3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer2/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangebuyer2/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangeseller/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangeseller/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangeseller/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexchangeseller/v2.0' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexperiencereport/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adexperiencereport/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/admin/datatransfer_v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/admin/directory_v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/admin/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/admin/reports_v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adsense/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adsense/v1.4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adsensehost/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/adsensehost/v4.1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analytics/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analytics/v2.4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analytics/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analyticsreporting/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/analyticsreporting/v4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androiddeviceprovisioning/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androiddeviceprovisioning/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidenterprise/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidenterprise/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidmanagement/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidmanagement/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/v1.1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/androidpublisher/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appengine/v1beta5' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appsactivity/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appsactivity/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appstate/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/appstate/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/bigquery/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/bigquery/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/bigquerydatatransfer/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/bigquerydatatransfer/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/blogger/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/blogger/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/blogger/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/books/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/books/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/calendar/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/calendar/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/chat/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/chat/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/civicinfo/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/civicinfo/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/classroom/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/classroom/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudbilling/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudbilling/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudbuild/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudbuild/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouddebugger/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouddebugger/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouderrorreporting/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/clouderrorreporting/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudfunctions/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudfunctions/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudfunctions/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudiot/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudiot/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudkms/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudkms/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudresourcemanager/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudshell/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudshell/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudshell/v1alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtasks/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtasks/v2beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtrace/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtrace/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/cloudtrace/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/composer/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/composer/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/compute/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/compute/beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/compute/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/compute/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/container/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/container/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/container/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/content/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/content/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/content/v2sandbox' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/customsearch/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/customsearch/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataflow/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataflow/v1b3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataproc/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataproc/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dataproc/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/datastore/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/datastore/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/datastore/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/datastore/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/deploymentmanager/alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/deploymentmanager/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/deploymentmanager/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/deploymentmanager/v2beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dfareporting/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dfareporting/v2.8' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dfareporting/v3.0' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dfareporting/v3.1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dialogflow/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dialogflow/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dialogflow/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/digitalassetlinks/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/digitalassetlinks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/discovery/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/discovery/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dlp/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dlp/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dns/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dns/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dns/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/dns/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/doubleclickbidmanager/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/doubleclickbidmanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/doubleclicksearch/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/doubleclicksearch/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/drive/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/drive/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/drive/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firebasedynamiclinks/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firebasedynamiclinks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firebaserules/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firebaserules/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firestore/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/firestore/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fitness/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fitness/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fusiontables/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fusiontables/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/fusiontables/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/games/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/games/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gamesConfiguration/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gamesConfiguration/v1configuration' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gamesManagement/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gamesManagement/v1management' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/genomics/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/genomics/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/genomics/v1alpha2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/genomics/v2alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gmail/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/gmail/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/groupsmigration/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/groupsmigration/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/groupssettings/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/groupssettings/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/iam/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/iam/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/identitytoolkit/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/identitytoolkit/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/jobs/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/jobs/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/kgsearch/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/kgsearch/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/language/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/language/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/language/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/language/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/licensing/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/licensing/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/logging/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/logging/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/logging/v2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/manufacturers/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/manufacturers/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/mirror/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/mirror/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/ml/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/ml/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/monitoring/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/monitoring/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oauth2/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oauth2/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oauth2/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oslogin/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oslogin/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oslogin/v1alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/oslogin/v1beta' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pagespeedonline/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pagespeedonline/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pagespeedonline/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pagespeedonline/v4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/partners/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/partners/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/people/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/people/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/playcustomapp/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/playcustomapp/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/plus/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/plus/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/plusDomains/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/plusDomains/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/poly/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/poly/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/proximitybeacon/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/proximitybeacon/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pubsub/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pubsub/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pubsub/v1beta1a' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/pubsub/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/redis/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/redis/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapool/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapool/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapool/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapoolupdater/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/replicapoolupdater/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/reseller/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/reseller/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/runtimeconfig/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/runtimeconfig/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/runtimeconfig/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/safebrowsing/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/safebrowsing/v4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/script/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/script/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/searchconsole/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/searchconsole/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicebroker/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicebroker/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicebroker/v1alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicebroker/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceconsumermanagement/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceconsumermanagement/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicecontrol/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicecontrol/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicemanagement/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/servicemanagement/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceusage/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceusage/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceuser/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/serviceuser/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sheets/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sheets/v4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/siteVerification/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/siteVerification/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/slides/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/slides/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sourcerepo/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sourcerepo/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/spanner/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/spanner/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/spectrum/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/spectrum/v1explorer' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/speech/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/speech/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/speech/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sqladmin/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sqladmin/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/sqladmin/v1beta4' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storage/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storage/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storage/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storage/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storagetransfer/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/storagetransfer/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/streetviewpublish/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/streetviewpublish/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/surveys/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/surveys/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tagmanager/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tagmanager/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tagmanager/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tasks/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tasks/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/testing/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/testing/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/texttospeech/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/texttospeech/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/toolresults/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/toolresults/v1beta3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tpu/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tpu/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/tpu/v1alpha1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/translate/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/translate/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/urlshortener/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/urlshortener/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vault/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vault/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/videointelligence/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/videointelligence/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/videointelligence/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/videointelligence/v1beta2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vision/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vision/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vision/v1p1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/vision/v1p2beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/webfonts/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/webfonts/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/webmasters/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/webmasters/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/websecurityscanner/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/websecurityscanner/v1alpha' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtube/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtube/v3' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubeAnalytics/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubeAnalytics/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubeAnalytics/v1beta1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubeAnalytics/v2' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubereporting/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/apis/youtubereporting/v1' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/generator/generate' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/generator/generator' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/googleapis' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/shared/src/api' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/shared/src/apiIndex' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/shared/src/apirequest' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/shared/src/discovery' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/shared/src/endpoint' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/shared/src/index' {
  declare module.exports: any;
}

declare module 'googleapis/build/src/shared/src/schema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'googleapis/build/src/apis/abusiveexperiencereport/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/abusiveexperiencereport/index'>;
}
declare module 'googleapis/build/src/apis/abusiveexperiencereport/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/abusiveexperiencereport/v1'>;
}
declare module 'googleapis/build/src/apis/acceleratedmobilepageurl/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/acceleratedmobilepageurl/index'>;
}
declare module 'googleapis/build/src/apis/acceleratedmobilepageurl/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/acceleratedmobilepageurl/v1'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer/index'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer/v1.2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer/v1.2'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer/v1.3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer/v1.3'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer/v1.4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer/v1.4'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer2/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer2/index'>;
}
declare module 'googleapis/build/src/apis/adexchangebuyer2/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangebuyer2/v2beta1'>;
}
declare module 'googleapis/build/src/apis/adexchangeseller/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangeseller/index'>;
}
declare module 'googleapis/build/src/apis/adexchangeseller/v1.1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangeseller/v1.1'>;
}
declare module 'googleapis/build/src/apis/adexchangeseller/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangeseller/v1'>;
}
declare module 'googleapis/build/src/apis/adexchangeseller/v2.0.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexchangeseller/v2.0'>;
}
declare module 'googleapis/build/src/apis/adexperiencereport/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexperiencereport/index'>;
}
declare module 'googleapis/build/src/apis/adexperiencereport/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adexperiencereport/v1'>;
}
declare module 'googleapis/build/src/apis/admin/datatransfer_v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/admin/datatransfer_v1'>;
}
declare module 'googleapis/build/src/apis/admin/directory_v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/admin/directory_v1'>;
}
declare module 'googleapis/build/src/apis/admin/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/admin/index'>;
}
declare module 'googleapis/build/src/apis/admin/reports_v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/admin/reports_v1'>;
}
declare module 'googleapis/build/src/apis/adsense/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adsense/index'>;
}
declare module 'googleapis/build/src/apis/adsense/v1.4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adsense/v1.4'>;
}
declare module 'googleapis/build/src/apis/adsensehost/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adsensehost/index'>;
}
declare module 'googleapis/build/src/apis/adsensehost/v4.1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/adsensehost/v4.1'>;
}
declare module 'googleapis/build/src/apis/analytics/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analytics/index'>;
}
declare module 'googleapis/build/src/apis/analytics/v2.4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analytics/v2.4'>;
}
declare module 'googleapis/build/src/apis/analytics/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analytics/v3'>;
}
declare module 'googleapis/build/src/apis/analyticsreporting/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analyticsreporting/index'>;
}
declare module 'googleapis/build/src/apis/analyticsreporting/v4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/analyticsreporting/v4'>;
}
declare module 'googleapis/build/src/apis/androiddeviceprovisioning/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androiddeviceprovisioning/index'>;
}
declare module 'googleapis/build/src/apis/androiddeviceprovisioning/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androiddeviceprovisioning/v1'>;
}
declare module 'googleapis/build/src/apis/androidenterprise/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidenterprise/index'>;
}
declare module 'googleapis/build/src/apis/androidenterprise/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidenterprise/v1'>;
}
declare module 'googleapis/build/src/apis/androidmanagement/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidmanagement/index'>;
}
declare module 'googleapis/build/src/apis/androidmanagement/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidmanagement/v1'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/index'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/v1.1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/v1.1'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/v1'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/v2'>;
}
declare module 'googleapis/build/src/apis/androidpublisher/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/androidpublisher/v3'>;
}
declare module 'googleapis/build/src/apis/appengine/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/index'>;
}
declare module 'googleapis/build/src/apis/appengine/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1'>;
}
declare module 'googleapis/build/src/apis/appengine/v1alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1alpha'>;
}
declare module 'googleapis/build/src/apis/appengine/v1beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1beta'>;
}
declare module 'googleapis/build/src/apis/appengine/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1beta4'>;
}
declare module 'googleapis/build/src/apis/appengine/v1beta5.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appengine/v1beta5'>;
}
declare module 'googleapis/build/src/apis/appsactivity/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appsactivity/index'>;
}
declare module 'googleapis/build/src/apis/appsactivity/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appsactivity/v1'>;
}
declare module 'googleapis/build/src/apis/appstate/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appstate/index'>;
}
declare module 'googleapis/build/src/apis/appstate/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/appstate/v1'>;
}
declare module 'googleapis/build/src/apis/bigquery/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/bigquery/index'>;
}
declare module 'googleapis/build/src/apis/bigquery/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/bigquery/v2'>;
}
declare module 'googleapis/build/src/apis/bigquerydatatransfer/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/bigquerydatatransfer/index'>;
}
declare module 'googleapis/build/src/apis/bigquerydatatransfer/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/bigquerydatatransfer/v1'>;
}
declare module 'googleapis/build/src/apis/blogger/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/blogger/index'>;
}
declare module 'googleapis/build/src/apis/blogger/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/blogger/v2'>;
}
declare module 'googleapis/build/src/apis/blogger/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/blogger/v3'>;
}
declare module 'googleapis/build/src/apis/books/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/books/index'>;
}
declare module 'googleapis/build/src/apis/books/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/books/v1'>;
}
declare module 'googleapis/build/src/apis/calendar/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/calendar/index'>;
}
declare module 'googleapis/build/src/apis/calendar/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/calendar/v3'>;
}
declare module 'googleapis/build/src/apis/chat/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/chat/index'>;
}
declare module 'googleapis/build/src/apis/chat/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/chat/v1'>;
}
declare module 'googleapis/build/src/apis/civicinfo/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/civicinfo/index'>;
}
declare module 'googleapis/build/src/apis/civicinfo/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/civicinfo/v2'>;
}
declare module 'googleapis/build/src/apis/classroom/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/classroom/index'>;
}
declare module 'googleapis/build/src/apis/classroom/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/classroom/v1'>;
}
declare module 'googleapis/build/src/apis/cloudbilling/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudbilling/index'>;
}
declare module 'googleapis/build/src/apis/cloudbilling/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudbilling/v1'>;
}
declare module 'googleapis/build/src/apis/cloudbuild/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudbuild/index'>;
}
declare module 'googleapis/build/src/apis/cloudbuild/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudbuild/v1'>;
}
declare module 'googleapis/build/src/apis/clouddebugger/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouddebugger/index'>;
}
declare module 'googleapis/build/src/apis/clouddebugger/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouddebugger/v2'>;
}
declare module 'googleapis/build/src/apis/clouderrorreporting/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouderrorreporting/index'>;
}
declare module 'googleapis/build/src/apis/clouderrorreporting/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/clouderrorreporting/v1beta1'>;
}
declare module 'googleapis/build/src/apis/cloudfunctions/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudfunctions/index'>;
}
declare module 'googleapis/build/src/apis/cloudfunctions/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudfunctions/v1'>;
}
declare module 'googleapis/build/src/apis/cloudfunctions/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudfunctions/v1beta2'>;
}
declare module 'googleapis/build/src/apis/cloudiot/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudiot/index'>;
}
declare module 'googleapis/build/src/apis/cloudiot/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudiot/v1'>;
}
declare module 'googleapis/build/src/apis/cloudkms/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudkms/index'>;
}
declare module 'googleapis/build/src/apis/cloudkms/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudkms/v1'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/index'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/v1'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/v1beta1'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/v2'>;
}
declare module 'googleapis/build/src/apis/cloudresourcemanager/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudresourcemanager/v2beta1'>;
}
declare module 'googleapis/build/src/apis/cloudshell/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudshell/index'>;
}
declare module 'googleapis/build/src/apis/cloudshell/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudshell/v1'>;
}
declare module 'googleapis/build/src/apis/cloudshell/v1alpha1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudshell/v1alpha1'>;
}
declare module 'googleapis/build/src/apis/cloudtasks/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtasks/index'>;
}
declare module 'googleapis/build/src/apis/cloudtasks/v2beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtasks/v2beta2'>;
}
declare module 'googleapis/build/src/apis/cloudtrace/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtrace/index'>;
}
declare module 'googleapis/build/src/apis/cloudtrace/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtrace/v1'>;
}
declare module 'googleapis/build/src/apis/cloudtrace/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/cloudtrace/v2'>;
}
declare module 'googleapis/build/src/apis/composer/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/composer/index'>;
}
declare module 'googleapis/build/src/apis/composer/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/composer/v1beta1'>;
}
declare module 'googleapis/build/src/apis/compute/alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/compute/alpha'>;
}
declare module 'googleapis/build/src/apis/compute/beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/compute/beta'>;
}
declare module 'googleapis/build/src/apis/compute/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/compute/index'>;
}
declare module 'googleapis/build/src/apis/compute/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/compute/v1'>;
}
declare module 'googleapis/build/src/apis/container/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/container/index'>;
}
declare module 'googleapis/build/src/apis/container/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/container/v1'>;
}
declare module 'googleapis/build/src/apis/container/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/container/v1beta1'>;
}
declare module 'googleapis/build/src/apis/content/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/content/index'>;
}
declare module 'googleapis/build/src/apis/content/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/content/v2'>;
}
declare module 'googleapis/build/src/apis/content/v2sandbox.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/content/v2sandbox'>;
}
declare module 'googleapis/build/src/apis/customsearch/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/customsearch/index'>;
}
declare module 'googleapis/build/src/apis/customsearch/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/customsearch/v1'>;
}
declare module 'googleapis/build/src/apis/dataflow/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataflow/index'>;
}
declare module 'googleapis/build/src/apis/dataflow/v1b3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataflow/v1b3'>;
}
declare module 'googleapis/build/src/apis/dataproc/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataproc/index'>;
}
declare module 'googleapis/build/src/apis/dataproc/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataproc/v1'>;
}
declare module 'googleapis/build/src/apis/dataproc/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dataproc/v1beta2'>;
}
declare module 'googleapis/build/src/apis/datastore/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/datastore/index'>;
}
declare module 'googleapis/build/src/apis/datastore/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/datastore/v1'>;
}
declare module 'googleapis/build/src/apis/datastore/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/datastore/v1beta1'>;
}
declare module 'googleapis/build/src/apis/datastore/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/datastore/v1beta3'>;
}
declare module 'googleapis/build/src/apis/deploymentmanager/alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/deploymentmanager/alpha'>;
}
declare module 'googleapis/build/src/apis/deploymentmanager/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/deploymentmanager/index'>;
}
declare module 'googleapis/build/src/apis/deploymentmanager/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/deploymentmanager/v2'>;
}
declare module 'googleapis/build/src/apis/deploymentmanager/v2beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/deploymentmanager/v2beta'>;
}
declare module 'googleapis/build/src/apis/dfareporting/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dfareporting/index'>;
}
declare module 'googleapis/build/src/apis/dfareporting/v2.8.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dfareporting/v2.8'>;
}
declare module 'googleapis/build/src/apis/dfareporting/v3.0.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dfareporting/v3.0'>;
}
declare module 'googleapis/build/src/apis/dfareporting/v3.1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dfareporting/v3.1'>;
}
declare module 'googleapis/build/src/apis/dialogflow/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dialogflow/index'>;
}
declare module 'googleapis/build/src/apis/dialogflow/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dialogflow/v2'>;
}
declare module 'googleapis/build/src/apis/dialogflow/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dialogflow/v2beta1'>;
}
declare module 'googleapis/build/src/apis/digitalassetlinks/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/digitalassetlinks/index'>;
}
declare module 'googleapis/build/src/apis/digitalassetlinks/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/digitalassetlinks/v1'>;
}
declare module 'googleapis/build/src/apis/discovery/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/discovery/index'>;
}
declare module 'googleapis/build/src/apis/discovery/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/discovery/v1'>;
}
declare module 'googleapis/build/src/apis/dlp/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dlp/index'>;
}
declare module 'googleapis/build/src/apis/dlp/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dlp/v2'>;
}
declare module 'googleapis/build/src/apis/dns/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dns/index'>;
}
declare module 'googleapis/build/src/apis/dns/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dns/v1'>;
}
declare module 'googleapis/build/src/apis/dns/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dns/v1beta2'>;
}
declare module 'googleapis/build/src/apis/dns/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/dns/v2beta1'>;
}
declare module 'googleapis/build/src/apis/doubleclickbidmanager/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/doubleclickbidmanager/index'>;
}
declare module 'googleapis/build/src/apis/doubleclickbidmanager/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/doubleclickbidmanager/v1'>;
}
declare module 'googleapis/build/src/apis/doubleclicksearch/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/doubleclicksearch/index'>;
}
declare module 'googleapis/build/src/apis/doubleclicksearch/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/doubleclicksearch/v2'>;
}
declare module 'googleapis/build/src/apis/drive/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/drive/index'>;
}
declare module 'googleapis/build/src/apis/drive/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/drive/v2'>;
}
declare module 'googleapis/build/src/apis/drive/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/drive/v3'>;
}
declare module 'googleapis/build/src/apis/firebasedynamiclinks/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firebasedynamiclinks/index'>;
}
declare module 'googleapis/build/src/apis/firebasedynamiclinks/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firebasedynamiclinks/v1'>;
}
declare module 'googleapis/build/src/apis/firebaserules/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firebaserules/index'>;
}
declare module 'googleapis/build/src/apis/firebaserules/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firebaserules/v1'>;
}
declare module 'googleapis/build/src/apis/firestore/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firestore/index'>;
}
declare module 'googleapis/build/src/apis/firestore/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/firestore/v1beta1'>;
}
declare module 'googleapis/build/src/apis/fitness/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fitness/index'>;
}
declare module 'googleapis/build/src/apis/fitness/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fitness/v1'>;
}
declare module 'googleapis/build/src/apis/fusiontables/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fusiontables/index'>;
}
declare module 'googleapis/build/src/apis/fusiontables/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fusiontables/v1'>;
}
declare module 'googleapis/build/src/apis/fusiontables/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/fusiontables/v2'>;
}
declare module 'googleapis/build/src/apis/games/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/games/index'>;
}
declare module 'googleapis/build/src/apis/games/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/games/v1'>;
}
declare module 'googleapis/build/src/apis/gamesConfiguration/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gamesConfiguration/index'>;
}
declare module 'googleapis/build/src/apis/gamesConfiguration/v1configuration.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gamesConfiguration/v1configuration'>;
}
declare module 'googleapis/build/src/apis/gamesManagement/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gamesManagement/index'>;
}
declare module 'googleapis/build/src/apis/gamesManagement/v1management.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gamesManagement/v1management'>;
}
declare module 'googleapis/build/src/apis/genomics/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/genomics/index'>;
}
declare module 'googleapis/build/src/apis/genomics/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/genomics/v1'>;
}
declare module 'googleapis/build/src/apis/genomics/v1alpha2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/genomics/v1alpha2'>;
}
declare module 'googleapis/build/src/apis/genomics/v2alpha1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/genomics/v2alpha1'>;
}
declare module 'googleapis/build/src/apis/gmail/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gmail/index'>;
}
declare module 'googleapis/build/src/apis/gmail/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/gmail/v1'>;
}
declare module 'googleapis/build/src/apis/groupsmigration/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/groupsmigration/index'>;
}
declare module 'googleapis/build/src/apis/groupsmigration/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/groupsmigration/v1'>;
}
declare module 'googleapis/build/src/apis/groupssettings/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/groupssettings/index'>;
}
declare module 'googleapis/build/src/apis/groupssettings/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/groupssettings/v1'>;
}
declare module 'googleapis/build/src/apis/iam/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/iam/index'>;
}
declare module 'googleapis/build/src/apis/iam/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/iam/v1'>;
}
declare module 'googleapis/build/src/apis/identitytoolkit/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/identitytoolkit/index'>;
}
declare module 'googleapis/build/src/apis/identitytoolkit/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/identitytoolkit/v3'>;
}
declare module 'googleapis/build/src/apis/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/index'>;
}
declare module 'googleapis/build/src/apis/jobs/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/jobs/index'>;
}
declare module 'googleapis/build/src/apis/jobs/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/jobs/v2'>;
}
declare module 'googleapis/build/src/apis/kgsearch/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/kgsearch/index'>;
}
declare module 'googleapis/build/src/apis/kgsearch/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/kgsearch/v1'>;
}
declare module 'googleapis/build/src/apis/language/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/language/index'>;
}
declare module 'googleapis/build/src/apis/language/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/language/v1'>;
}
declare module 'googleapis/build/src/apis/language/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/language/v1beta1'>;
}
declare module 'googleapis/build/src/apis/language/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/language/v1beta2'>;
}
declare module 'googleapis/build/src/apis/licensing/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/licensing/index'>;
}
declare module 'googleapis/build/src/apis/licensing/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/licensing/v1'>;
}
declare module 'googleapis/build/src/apis/logging/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/logging/index'>;
}
declare module 'googleapis/build/src/apis/logging/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/logging/v2'>;
}
declare module 'googleapis/build/src/apis/logging/v2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/logging/v2beta1'>;
}
declare module 'googleapis/build/src/apis/manufacturers/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/manufacturers/index'>;
}
declare module 'googleapis/build/src/apis/manufacturers/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/manufacturers/v1'>;
}
declare module 'googleapis/build/src/apis/mirror/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/mirror/index'>;
}
declare module 'googleapis/build/src/apis/mirror/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/mirror/v1'>;
}
declare module 'googleapis/build/src/apis/ml/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/ml/index'>;
}
declare module 'googleapis/build/src/apis/ml/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/ml/v1'>;
}
declare module 'googleapis/build/src/apis/monitoring/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/monitoring/index'>;
}
declare module 'googleapis/build/src/apis/monitoring/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/monitoring/v3'>;
}
declare module 'googleapis/build/src/apis/oauth2/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oauth2/index'>;
}
declare module 'googleapis/build/src/apis/oauth2/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oauth2/v1'>;
}
declare module 'googleapis/build/src/apis/oauth2/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oauth2/v2'>;
}
declare module 'googleapis/build/src/apis/oslogin/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oslogin/index'>;
}
declare module 'googleapis/build/src/apis/oslogin/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oslogin/v1'>;
}
declare module 'googleapis/build/src/apis/oslogin/v1alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oslogin/v1alpha'>;
}
declare module 'googleapis/build/src/apis/oslogin/v1beta.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/oslogin/v1beta'>;
}
declare module 'googleapis/build/src/apis/pagespeedonline/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pagespeedonline/index'>;
}
declare module 'googleapis/build/src/apis/pagespeedonline/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pagespeedonline/v1'>;
}
declare module 'googleapis/build/src/apis/pagespeedonline/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pagespeedonline/v2'>;
}
declare module 'googleapis/build/src/apis/pagespeedonline/v4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pagespeedonline/v4'>;
}
declare module 'googleapis/build/src/apis/partners/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/partners/index'>;
}
declare module 'googleapis/build/src/apis/partners/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/partners/v2'>;
}
declare module 'googleapis/build/src/apis/people/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/people/index'>;
}
declare module 'googleapis/build/src/apis/people/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/people/v1'>;
}
declare module 'googleapis/build/src/apis/playcustomapp/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/playcustomapp/index'>;
}
declare module 'googleapis/build/src/apis/playcustomapp/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/playcustomapp/v1'>;
}
declare module 'googleapis/build/src/apis/plus/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/plus/index'>;
}
declare module 'googleapis/build/src/apis/plus/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/plus/v1'>;
}
declare module 'googleapis/build/src/apis/plusDomains/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/plusDomains/index'>;
}
declare module 'googleapis/build/src/apis/plusDomains/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/plusDomains/v1'>;
}
declare module 'googleapis/build/src/apis/poly/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/poly/index'>;
}
declare module 'googleapis/build/src/apis/poly/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/poly/v1'>;
}
declare module 'googleapis/build/src/apis/proximitybeacon/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/proximitybeacon/index'>;
}
declare module 'googleapis/build/src/apis/proximitybeacon/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/proximitybeacon/v1beta1'>;
}
declare module 'googleapis/build/src/apis/pubsub/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pubsub/index'>;
}
declare module 'googleapis/build/src/apis/pubsub/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pubsub/v1'>;
}
declare module 'googleapis/build/src/apis/pubsub/v1beta1a.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pubsub/v1beta1a'>;
}
declare module 'googleapis/build/src/apis/pubsub/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/pubsub/v1beta2'>;
}
declare module 'googleapis/build/src/apis/redis/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/redis/index'>;
}
declare module 'googleapis/build/src/apis/redis/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/redis/v1beta1'>;
}
declare module 'googleapis/build/src/apis/replicapool/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapool/index'>;
}
declare module 'googleapis/build/src/apis/replicapool/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapool/v1beta1'>;
}
declare module 'googleapis/build/src/apis/replicapool/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapool/v1beta2'>;
}
declare module 'googleapis/build/src/apis/replicapoolupdater/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapoolupdater/index'>;
}
declare module 'googleapis/build/src/apis/replicapoolupdater/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/replicapoolupdater/v1beta1'>;
}
declare module 'googleapis/build/src/apis/reseller/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/reseller/index'>;
}
declare module 'googleapis/build/src/apis/reseller/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/reseller/v1'>;
}
declare module 'googleapis/build/src/apis/runtimeconfig/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/runtimeconfig/index'>;
}
declare module 'googleapis/build/src/apis/runtimeconfig/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/runtimeconfig/v1'>;
}
declare module 'googleapis/build/src/apis/runtimeconfig/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/runtimeconfig/v1beta1'>;
}
declare module 'googleapis/build/src/apis/safebrowsing/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/safebrowsing/index'>;
}
declare module 'googleapis/build/src/apis/safebrowsing/v4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/safebrowsing/v4'>;
}
declare module 'googleapis/build/src/apis/script/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/script/index'>;
}
declare module 'googleapis/build/src/apis/script/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/script/v1'>;
}
declare module 'googleapis/build/src/apis/searchconsole/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/searchconsole/index'>;
}
declare module 'googleapis/build/src/apis/searchconsole/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/searchconsole/v1'>;
}
declare module 'googleapis/build/src/apis/servicebroker/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicebroker/index'>;
}
declare module 'googleapis/build/src/apis/servicebroker/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicebroker/v1'>;
}
declare module 'googleapis/build/src/apis/servicebroker/v1alpha1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicebroker/v1alpha1'>;
}
declare module 'googleapis/build/src/apis/servicebroker/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicebroker/v1beta1'>;
}
declare module 'googleapis/build/src/apis/serviceconsumermanagement/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceconsumermanagement/index'>;
}
declare module 'googleapis/build/src/apis/serviceconsumermanagement/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceconsumermanagement/v1'>;
}
declare module 'googleapis/build/src/apis/servicecontrol/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicecontrol/index'>;
}
declare module 'googleapis/build/src/apis/servicecontrol/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicecontrol/v1'>;
}
declare module 'googleapis/build/src/apis/servicemanagement/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicemanagement/index'>;
}
declare module 'googleapis/build/src/apis/servicemanagement/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/servicemanagement/v1'>;
}
declare module 'googleapis/build/src/apis/serviceusage/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceusage/index'>;
}
declare module 'googleapis/build/src/apis/serviceusage/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceusage/v1beta1'>;
}
declare module 'googleapis/build/src/apis/serviceuser/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceuser/index'>;
}
declare module 'googleapis/build/src/apis/serviceuser/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/serviceuser/v1'>;
}
declare module 'googleapis/build/src/apis/sheets/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sheets/index'>;
}
declare module 'googleapis/build/src/apis/sheets/v4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sheets/v4'>;
}
declare module 'googleapis/build/src/apis/siteVerification/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/siteVerification/index'>;
}
declare module 'googleapis/build/src/apis/siteVerification/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/siteVerification/v1'>;
}
declare module 'googleapis/build/src/apis/slides/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/slides/index'>;
}
declare module 'googleapis/build/src/apis/slides/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/slides/v1'>;
}
declare module 'googleapis/build/src/apis/sourcerepo/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sourcerepo/index'>;
}
declare module 'googleapis/build/src/apis/sourcerepo/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sourcerepo/v1'>;
}
declare module 'googleapis/build/src/apis/spanner/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/spanner/index'>;
}
declare module 'googleapis/build/src/apis/spanner/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/spanner/v1'>;
}
declare module 'googleapis/build/src/apis/spectrum/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/spectrum/index'>;
}
declare module 'googleapis/build/src/apis/spectrum/v1explorer.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/spectrum/v1explorer'>;
}
declare module 'googleapis/build/src/apis/speech/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/speech/index'>;
}
declare module 'googleapis/build/src/apis/speech/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/speech/v1'>;
}
declare module 'googleapis/build/src/apis/speech/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/speech/v1beta1'>;
}
declare module 'googleapis/build/src/apis/sqladmin/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sqladmin/index'>;
}
declare module 'googleapis/build/src/apis/sqladmin/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sqladmin/v1beta3'>;
}
declare module 'googleapis/build/src/apis/sqladmin/v1beta4.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/sqladmin/v1beta4'>;
}
declare module 'googleapis/build/src/apis/storage/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storage/index'>;
}
declare module 'googleapis/build/src/apis/storage/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storage/v1'>;
}
declare module 'googleapis/build/src/apis/storage/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storage/v1beta1'>;
}
declare module 'googleapis/build/src/apis/storage/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storage/v1beta2'>;
}
declare module 'googleapis/build/src/apis/storagetransfer/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storagetransfer/index'>;
}
declare module 'googleapis/build/src/apis/storagetransfer/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/storagetransfer/v1'>;
}
declare module 'googleapis/build/src/apis/streetviewpublish/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/streetviewpublish/index'>;
}
declare module 'googleapis/build/src/apis/streetviewpublish/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/streetviewpublish/v1'>;
}
declare module 'googleapis/build/src/apis/surveys/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/surveys/index'>;
}
declare module 'googleapis/build/src/apis/surveys/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/surveys/v2'>;
}
declare module 'googleapis/build/src/apis/tagmanager/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tagmanager/index'>;
}
declare module 'googleapis/build/src/apis/tagmanager/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tagmanager/v1'>;
}
declare module 'googleapis/build/src/apis/tagmanager/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tagmanager/v2'>;
}
declare module 'googleapis/build/src/apis/tasks/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tasks/index'>;
}
declare module 'googleapis/build/src/apis/tasks/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tasks/v1'>;
}
declare module 'googleapis/build/src/apis/testing/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/testing/index'>;
}
declare module 'googleapis/build/src/apis/testing/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/testing/v1'>;
}
declare module 'googleapis/build/src/apis/texttospeech/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/texttospeech/index'>;
}
declare module 'googleapis/build/src/apis/texttospeech/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/texttospeech/v1beta1'>;
}
declare module 'googleapis/build/src/apis/toolresults/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/toolresults/index'>;
}
declare module 'googleapis/build/src/apis/toolresults/v1beta3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/toolresults/v1beta3'>;
}
declare module 'googleapis/build/src/apis/tpu/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tpu/index'>;
}
declare module 'googleapis/build/src/apis/tpu/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tpu/v1'>;
}
declare module 'googleapis/build/src/apis/tpu/v1alpha1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/tpu/v1alpha1'>;
}
declare module 'googleapis/build/src/apis/translate/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/translate/index'>;
}
declare module 'googleapis/build/src/apis/translate/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/translate/v2'>;
}
declare module 'googleapis/build/src/apis/urlshortener/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/urlshortener/index'>;
}
declare module 'googleapis/build/src/apis/urlshortener/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/urlshortener/v1'>;
}
declare module 'googleapis/build/src/apis/vault/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vault/index'>;
}
declare module 'googleapis/build/src/apis/vault/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vault/v1'>;
}
declare module 'googleapis/build/src/apis/videointelligence/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/videointelligence/index'>;
}
declare module 'googleapis/build/src/apis/videointelligence/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/videointelligence/v1'>;
}
declare module 'googleapis/build/src/apis/videointelligence/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/videointelligence/v1beta1'>;
}
declare module 'googleapis/build/src/apis/videointelligence/v1beta2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/videointelligence/v1beta2'>;
}
declare module 'googleapis/build/src/apis/vision/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vision/index'>;
}
declare module 'googleapis/build/src/apis/vision/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vision/v1'>;
}
declare module 'googleapis/build/src/apis/vision/v1p1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vision/v1p1beta1'>;
}
declare module 'googleapis/build/src/apis/vision/v1p2beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/vision/v1p2beta1'>;
}
declare module 'googleapis/build/src/apis/webfonts/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/webfonts/index'>;
}
declare module 'googleapis/build/src/apis/webfonts/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/webfonts/v1'>;
}
declare module 'googleapis/build/src/apis/webmasters/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/webmasters/index'>;
}
declare module 'googleapis/build/src/apis/webmasters/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/webmasters/v3'>;
}
declare module 'googleapis/build/src/apis/websecurityscanner/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/websecurityscanner/index'>;
}
declare module 'googleapis/build/src/apis/websecurityscanner/v1alpha.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/websecurityscanner/v1alpha'>;
}
declare module 'googleapis/build/src/apis/youtube/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtube/index'>;
}
declare module 'googleapis/build/src/apis/youtube/v3.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtube/v3'>;
}
declare module 'googleapis/build/src/apis/youtubeAnalytics/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubeAnalytics/index'>;
}
declare module 'googleapis/build/src/apis/youtubeAnalytics/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubeAnalytics/v1'>;
}
declare module 'googleapis/build/src/apis/youtubeAnalytics/v1beta1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubeAnalytics/v1beta1'>;
}
declare module 'googleapis/build/src/apis/youtubeAnalytics/v2.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubeAnalytics/v2'>;
}
declare module 'googleapis/build/src/apis/youtubereporting/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubereporting/index'>;
}
declare module 'googleapis/build/src/apis/youtubereporting/v1.js' {
  declare module.exports: $Exports<'googleapis/build/src/apis/youtubereporting/v1'>;
}
declare module 'googleapis/build/src/generator/generate.js' {
  declare module.exports: $Exports<'googleapis/build/src/generator/generate'>;
}
declare module 'googleapis/build/src/generator/generator.js' {
  declare module.exports: $Exports<'googleapis/build/src/generator/generator'>;
}
declare module 'googleapis/build/src/googleapis.js' {
  declare module.exports: $Exports<'googleapis/build/src/googleapis'>;
}
declare module 'googleapis/build/src/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/index'>;
}
declare module 'googleapis/build/src/shared/src/api.js' {
  declare module.exports: $Exports<'googleapis/build/src/shared/src/api'>;
}
declare module 'googleapis/build/src/shared/src/apiIndex.js' {
  declare module.exports: $Exports<'googleapis/build/src/shared/src/apiIndex'>;
}
declare module 'googleapis/build/src/shared/src/apirequest.js' {
  declare module.exports: $Exports<'googleapis/build/src/shared/src/apirequest'>;
}
declare module 'googleapis/build/src/shared/src/discovery.js' {
  declare module.exports: $Exports<'googleapis/build/src/shared/src/discovery'>;
}
declare module 'googleapis/build/src/shared/src/endpoint.js' {
  declare module.exports: $Exports<'googleapis/build/src/shared/src/endpoint'>;
}
declare module 'googleapis/build/src/shared/src/index.js' {
  declare module.exports: $Exports<'googleapis/build/src/shared/src/index'>;
}
declare module 'googleapis/build/src/shared/src/schema.js' {
  declare module.exports: $Exports<'googleapis/build/src/shared/src/schema'>;
}
