// flow-typed signature: 0e55e31e746e1465b45e0b972c7baec1
// flow-typed version: <<STUB>>/graphql.macro_v^1.0.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql.macro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql.macro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql.macro/lib/index' {
  declare module.exports: any;
}

declare module 'graphql.macro/lib/macro' {
  declare module.exports: any;
}

declare module 'graphql.macro/lib/utils/compileWithFragment' {
  declare module.exports: any;
}

declare module 'graphql.macro/lib/utils/expandImports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql.macro/lib/index.js' {
  declare module.exports: $Exports<'graphql.macro/lib/index'>;
}
declare module 'graphql.macro/lib/macro.js' {
  declare module.exports: $Exports<'graphql.macro/lib/macro'>;
}
declare module 'graphql.macro/lib/utils/compileWithFragment.js' {
  declare module.exports: $Exports<'graphql.macro/lib/utils/compileWithFragment'>;
}
declare module 'graphql.macro/lib/utils/expandImports.js' {
  declare module.exports: $Exports<'graphql.macro/lib/utils/expandImports'>;
}
