// flow-typed signature: 91abebbdffb65a267e5a86712a1667a3
// flow-typed version: <<STUB>>/jss_v9.8.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss/dist/jss' {
  declare module.exports: any;
}

declare module 'jss/dist/jss.min' {
  declare module.exports: any;
}

declare module 'jss/lib/index' {
  declare module.exports: any;
}

declare module 'jss/lib/Jss' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/functions' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/observables' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/rules' {
  declare module.exports: any;
}

declare module 'jss/lib/PluginsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/renderers/DomRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/renderers/VirtualRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/RuleList' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/ConditionalRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/FontFaceRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/KeyframesRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/SimpleRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/StyleRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/ViewportRule' {
  declare module.exports: any;
}

declare module 'jss/lib/sheets' {
  declare module.exports: any;
}

declare module 'jss/lib/SheetsManager' {
  declare module.exports: any;
}

declare module 'jss/lib/SheetsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/StyleSheet' {
  declare module.exports: any;
}

declare module 'jss/lib/types/cssom' {
  declare module.exports: any;
}

declare module 'jss/lib/types/index' {
  declare module.exports: any;
}

declare module 'jss/lib/types/jss' {
  declare module.exports: any;
}

declare module 'jss/lib/types/observable' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/cloneStyle' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/createGenerateClassName' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/createRule' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/escape' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/getDynamicStyles' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/isObservable' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/linkRule' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/moduleId' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/toCss' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/toCssValue' {
  declare module.exports: any;
}

declare module 'jss/src/index' {
  declare module.exports: any;
}

declare module 'jss/src/Jss' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/functions' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/observables' {
  declare module.exports: any;
}

declare module 'jss/src/plugins/rules' {
  declare module.exports: any;
}

declare module 'jss/src/PluginsRegistry' {
  declare module.exports: any;
}

declare module 'jss/src/renderers/DomRenderer' {
  declare module.exports: any;
}

declare module 'jss/src/renderers/VirtualRenderer' {
  declare module.exports: any;
}

declare module 'jss/src/RuleList' {
  declare module.exports: any;
}

declare module 'jss/src/rules/ConditionalRule' {
  declare module.exports: any;
}

declare module 'jss/src/rules/FontFaceRule' {
  declare module.exports: any;
}

declare module 'jss/src/rules/KeyframesRule' {
  declare module.exports: any;
}

declare module 'jss/src/rules/SimpleRule' {
  declare module.exports: any;
}

declare module 'jss/src/rules/StyleRule' {
  declare module.exports: any;
}

declare module 'jss/src/rules/ViewportRule' {
  declare module.exports: any;
}

declare module 'jss/src/sheets' {
  declare module.exports: any;
}

declare module 'jss/src/SheetsManager' {
  declare module.exports: any;
}

declare module 'jss/src/SheetsRegistry' {
  declare module.exports: any;
}

declare module 'jss/src/StyleSheet' {
  declare module.exports: any;
}

declare module 'jss/src/types/cssom' {
  declare module.exports: any;
}

declare module 'jss/src/types/index' {
  declare module.exports: any;
}

declare module 'jss/src/types/jss' {
  declare module.exports: any;
}

declare module 'jss/src/types/observable' {
  declare module.exports: any;
}

declare module 'jss/src/utils/cloneStyle' {
  declare module.exports: any;
}

declare module 'jss/src/utils/createGenerateClassName' {
  declare module.exports: any;
}

declare module 'jss/src/utils/createRule' {
  declare module.exports: any;
}

declare module 'jss/src/utils/escape' {
  declare module.exports: any;
}

declare module 'jss/src/utils/getDynamicStyles' {
  declare module.exports: any;
}

declare module 'jss/src/utils/isObservable' {
  declare module.exports: any;
}

declare module 'jss/src/utils/linkRule' {
  declare module.exports: any;
}

declare module 'jss/src/utils/moduleId' {
  declare module.exports: any;
}

declare module 'jss/src/utils/toCss' {
  declare module.exports: any;
}

declare module 'jss/src/utils/toCssValue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss/dist/jss.js' {
  declare module.exports: $Exports<'jss/dist/jss'>;
}
declare module 'jss/dist/jss.min.js' {
  declare module.exports: $Exports<'jss/dist/jss.min'>;
}
declare module 'jss/lib/index.js' {
  declare module.exports: $Exports<'jss/lib/index'>;
}
declare module 'jss/lib/Jss.js' {
  declare module.exports: $Exports<'jss/lib/Jss'>;
}
declare module 'jss/lib/plugins/functions.js' {
  declare module.exports: $Exports<'jss/lib/plugins/functions'>;
}
declare module 'jss/lib/plugins/observables.js' {
  declare module.exports: $Exports<'jss/lib/plugins/observables'>;
}
declare module 'jss/lib/plugins/rules.js' {
  declare module.exports: $Exports<'jss/lib/plugins/rules'>;
}
declare module 'jss/lib/PluginsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/PluginsRegistry'>;
}
declare module 'jss/lib/renderers/DomRenderer.js' {
  declare module.exports: $Exports<'jss/lib/renderers/DomRenderer'>;
}
declare module 'jss/lib/renderers/VirtualRenderer.js' {
  declare module.exports: $Exports<'jss/lib/renderers/VirtualRenderer'>;
}
declare module 'jss/lib/RuleList.js' {
  declare module.exports: $Exports<'jss/lib/RuleList'>;
}
declare module 'jss/lib/rules/ConditionalRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/ConditionalRule'>;
}
declare module 'jss/lib/rules/FontFaceRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/FontFaceRule'>;
}
declare module 'jss/lib/rules/KeyframesRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/KeyframesRule'>;
}
declare module 'jss/lib/rules/SimpleRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/SimpleRule'>;
}
declare module 'jss/lib/rules/StyleRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/StyleRule'>;
}
declare module 'jss/lib/rules/ViewportRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/ViewportRule'>;
}
declare module 'jss/lib/sheets.js' {
  declare module.exports: $Exports<'jss/lib/sheets'>;
}
declare module 'jss/lib/SheetsManager.js' {
  declare module.exports: $Exports<'jss/lib/SheetsManager'>;
}
declare module 'jss/lib/SheetsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/SheetsRegistry'>;
}
declare module 'jss/lib/StyleSheet.js' {
  declare module.exports: $Exports<'jss/lib/StyleSheet'>;
}
declare module 'jss/lib/types/cssom.js' {
  declare module.exports: $Exports<'jss/lib/types/cssom'>;
}
declare module 'jss/lib/types/index.js' {
  declare module.exports: $Exports<'jss/lib/types/index'>;
}
declare module 'jss/lib/types/jss.js' {
  declare module.exports: $Exports<'jss/lib/types/jss'>;
}
declare module 'jss/lib/types/observable.js' {
  declare module.exports: $Exports<'jss/lib/types/observable'>;
}
declare module 'jss/lib/utils/cloneStyle.js' {
  declare module.exports: $Exports<'jss/lib/utils/cloneStyle'>;
}
declare module 'jss/lib/utils/createGenerateClassName.js' {
  declare module.exports: $Exports<'jss/lib/utils/createGenerateClassName'>;
}
declare module 'jss/lib/utils/createRule.js' {
  declare module.exports: $Exports<'jss/lib/utils/createRule'>;
}
declare module 'jss/lib/utils/escape.js' {
  declare module.exports: $Exports<'jss/lib/utils/escape'>;
}
declare module 'jss/lib/utils/getDynamicStyles.js' {
  declare module.exports: $Exports<'jss/lib/utils/getDynamicStyles'>;
}
declare module 'jss/lib/utils/isObservable.js' {
  declare module.exports: $Exports<'jss/lib/utils/isObservable'>;
}
declare module 'jss/lib/utils/linkRule.js' {
  declare module.exports: $Exports<'jss/lib/utils/linkRule'>;
}
declare module 'jss/lib/utils/moduleId.js' {
  declare module.exports: $Exports<'jss/lib/utils/moduleId'>;
}
declare module 'jss/lib/utils/toCss.js' {
  declare module.exports: $Exports<'jss/lib/utils/toCss'>;
}
declare module 'jss/lib/utils/toCssValue.js' {
  declare module.exports: $Exports<'jss/lib/utils/toCssValue'>;
}
declare module 'jss/src/index.js' {
  declare module.exports: $Exports<'jss/src/index'>;
}
declare module 'jss/src/Jss.js' {
  declare module.exports: $Exports<'jss/src/Jss'>;
}
declare module 'jss/src/plugins/functions.js' {
  declare module.exports: $Exports<'jss/src/plugins/functions'>;
}
declare module 'jss/src/plugins/observables.js' {
  declare module.exports: $Exports<'jss/src/plugins/observables'>;
}
declare module 'jss/src/plugins/rules.js' {
  declare module.exports: $Exports<'jss/src/plugins/rules'>;
}
declare module 'jss/src/PluginsRegistry.js' {
  declare module.exports: $Exports<'jss/src/PluginsRegistry'>;
}
declare module 'jss/src/renderers/DomRenderer.js' {
  declare module.exports: $Exports<'jss/src/renderers/DomRenderer'>;
}
declare module 'jss/src/renderers/VirtualRenderer.js' {
  declare module.exports: $Exports<'jss/src/renderers/VirtualRenderer'>;
}
declare module 'jss/src/RuleList.js' {
  declare module.exports: $Exports<'jss/src/RuleList'>;
}
declare module 'jss/src/rules/ConditionalRule.js' {
  declare module.exports: $Exports<'jss/src/rules/ConditionalRule'>;
}
declare module 'jss/src/rules/FontFaceRule.js' {
  declare module.exports: $Exports<'jss/src/rules/FontFaceRule'>;
}
declare module 'jss/src/rules/KeyframesRule.js' {
  declare module.exports: $Exports<'jss/src/rules/KeyframesRule'>;
}
declare module 'jss/src/rules/SimpleRule.js' {
  declare module.exports: $Exports<'jss/src/rules/SimpleRule'>;
}
declare module 'jss/src/rules/StyleRule.js' {
  declare module.exports: $Exports<'jss/src/rules/StyleRule'>;
}
declare module 'jss/src/rules/ViewportRule.js' {
  declare module.exports: $Exports<'jss/src/rules/ViewportRule'>;
}
declare module 'jss/src/sheets.js' {
  declare module.exports: $Exports<'jss/src/sheets'>;
}
declare module 'jss/src/SheetsManager.js' {
  declare module.exports: $Exports<'jss/src/SheetsManager'>;
}
declare module 'jss/src/SheetsRegistry.js' {
  declare module.exports: $Exports<'jss/src/SheetsRegistry'>;
}
declare module 'jss/src/StyleSheet.js' {
  declare module.exports: $Exports<'jss/src/StyleSheet'>;
}
declare module 'jss/src/types/cssom.js' {
  declare module.exports: $Exports<'jss/src/types/cssom'>;
}
declare module 'jss/src/types/index.js' {
  declare module.exports: $Exports<'jss/src/types/index'>;
}
declare module 'jss/src/types/jss.js' {
  declare module.exports: $Exports<'jss/src/types/jss'>;
}
declare module 'jss/src/types/observable.js' {
  declare module.exports: $Exports<'jss/src/types/observable'>;
}
declare module 'jss/src/utils/cloneStyle.js' {
  declare module.exports: $Exports<'jss/src/utils/cloneStyle'>;
}
declare module 'jss/src/utils/createGenerateClassName.js' {
  declare module.exports: $Exports<'jss/src/utils/createGenerateClassName'>;
}
declare module 'jss/src/utils/createRule.js' {
  declare module.exports: $Exports<'jss/src/utils/createRule'>;
}
declare module 'jss/src/utils/escape.js' {
  declare module.exports: $Exports<'jss/src/utils/escape'>;
}
declare module 'jss/src/utils/getDynamicStyles.js' {
  declare module.exports: $Exports<'jss/src/utils/getDynamicStyles'>;
}
declare module 'jss/src/utils/isObservable.js' {
  declare module.exports: $Exports<'jss/src/utils/isObservable'>;
}
declare module 'jss/src/utils/linkRule.js' {
  declare module.exports: $Exports<'jss/src/utils/linkRule'>;
}
declare module 'jss/src/utils/moduleId.js' {
  declare module.exports: $Exports<'jss/src/utils/moduleId'>;
}
declare module 'jss/src/utils/toCss.js' {
  declare module.exports: $Exports<'jss/src/utils/toCss'>;
}
declare module 'jss/src/utils/toCssValue.js' {
  declare module.exports: $Exports<'jss/src/utils/toCssValue'>;
}
