// flow-typed signature: 4a0ab412c26e5c5dacb5d10a620d3e1c
// flow-typed version: <<STUB>>/mcs-f2e-translation_v^0.7.4/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-f2e-translation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-f2e-translation' {
  declare module.exports: any;
}
