// flow-typed signature: 3888f54b699f12ec472e9b49cef7de7e
// flow-typed version: <<STUB>>/mcs-lite-ui_v^0.8.13/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-lite-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-lite-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mcs-lite-ui/lib/A/A' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/A/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Avatar/Avatar' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Avatar/IconAvatar' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Avatar/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Avatar/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/B/B' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/B/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Breadcrumb/Breadcrumb' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Breadcrumb/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Button/Button' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Button/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Button/propMappers' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Card/Card' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Card/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Checkbox/Checkbox' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Checkbox/IconCheck' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Checkbox/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Checkbox/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Code/Code' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Code/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/CopyButton/CopyButton' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/CopyButton/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/ButtonClear' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/ControlNumber' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/ControlPeriod' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/ControlRange' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/ControlString' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/ControlSwitch' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/DisplayMultipleValue' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/DisplayStatus' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/DisplayString' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/DisplayUnitValue' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannel/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannelAdapter/API' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannelAdapter/DataChannelAdapter' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannelAdapter/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannelCard/DataChannelCard' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataChannelCard/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataPointAreaChart/DataPointAreaChart' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataPointAreaChart/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DataPointAreaChart/RechartTooltip' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DatetimePicker/DATE_API' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DatetimePicker/DatetimePicker' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DatetimePicker/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DatetimePicker/utils' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DatetimePickerDialog/DatetimePickerDialog' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DatetimePickerDialog/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Dialog/CommonDialog' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Dialog/Dialog' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Dialog/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DropdownMenu/DropdownMenu' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DropdownMenu/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DropdownMenu/position.config' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/DropdownMenu/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Form/ErrorMessage' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Form/Fieldset' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Form/Form' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Form/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Form/ResponsivePanel' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/FormGroup/FormGroup' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/FormGroup/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Heading/Heading' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Heading/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Hr/Hr' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Hr/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/IconWarning/IconWarning' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/IconWarning/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/ImageDropzone/Container' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/ImageDropzone/Image' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/ImageDropzone/ImageDropzone' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/ImageDropzone/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/ImageDropzone/LoadingWrapper' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Img/Img' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Img/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Input/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Input/Input' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputCheckbox/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputCheckbox/InputCheckbox' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputCheckbox/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputGroup/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputGroup/InputGroup' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputMultiSelect/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputMultiSelect/InputMultiSelect' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputOrder/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputOrder/InputOrder' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputOrder/Item' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputOrder/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputOrder/type.flow' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputRadio/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputRadio/InputRadio' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputRadio/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputRange/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputRange/InputRange' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputSelect/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputSelect/InputSelect' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputSelect/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputSelect/type.flow' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/InputSelect/utils' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Label/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Label/Label' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LandingHeader/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LandingHeader/LandingHeader' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LandingHeader/Nav' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LandingHeader/NavItem' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LandingHeader/NavItemBurger' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LandingHeader/NavItemDropdown' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LazyloadOnce/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/LazyloadOnce/LazyloadOnce' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Logo/MCS' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Menu/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Menu/Menu' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Menu/MenuItem' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileContentWrapper/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileContentWrapper/MobileContentWrapper' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileDeviceCard/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileDeviceCard/MobileDeviceCard' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileFixedFooter/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileFixedFooter/MobileFixedFooter' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileHeader/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileHeader/MobileHeader' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MobileHeader/MobileHeaderIcon' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MorphReplace/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/MorphReplace/MorphReplace' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Notification/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Notification/Notification' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Orderbox/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Orderbox/Orderbox' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Overlay/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Overlay/Overlay' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/P/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/P/P' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Panel/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Panel/Panel' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/PanelIcon/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/PanelIcon/PanelIcon' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Picker/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Picker/Picker' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Picker/PickerContainer' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Popover/Arrow' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Popover/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Popover/Popover' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Popover/position.config' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/PreventDrag/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/PreventDrag/PreventDrag' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/PullToRefresh/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/PullToRefresh/PullToRefresh' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Rotate/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Rotate/Rotate' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Select/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Select/Select' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Select/styled-components' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Select/type.flow' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Small/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Small/Small' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/SpaceTop/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/SpaceTop/SpaceTop' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Spin/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Spin/rotate360' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Spin/Spin' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/StatusLight/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/StatusLight/StatusLight' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Switch/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Switch/Switch' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/TabItem/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/TabItem/TabItem' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Table/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Table/Table' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Textarea/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Textarea/Textarea' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/TextCenter/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/TextCenter/TextCenter' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Toast/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Toast/Toast' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Tooltip/Arrow' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Tooltip/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Tooltip/position.config' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/Tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/cookieHelper' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/dataChannelHelper' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/emptyFunction' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/getCurrentYear' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/getScrollTop' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/isNumber' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/isString' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/localeHelper' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/localTimeFormat' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/osHelper' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/react-hammerjs' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/routerHelper' {
  declare module.exports: any;
}

declare module 'mcs-lite-ui/lib/utils/validators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mcs-lite-ui/lib/A/A.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/A/A'>;
}
declare module 'mcs-lite-ui/lib/A/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/A/index'>;
}
declare module 'mcs-lite-ui/lib/Avatar/Avatar.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Avatar/Avatar'>;
}
declare module 'mcs-lite-ui/lib/Avatar/IconAvatar.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Avatar/IconAvatar'>;
}
declare module 'mcs-lite-ui/lib/Avatar/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Avatar/index'>;
}
declare module 'mcs-lite-ui/lib/Avatar/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Avatar/styled-components'>;
}
declare module 'mcs-lite-ui/lib/B/B.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/B/B'>;
}
declare module 'mcs-lite-ui/lib/B/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/B/index'>;
}
declare module 'mcs-lite-ui/lib/Breadcrumb/Breadcrumb.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Breadcrumb/Breadcrumb'>;
}
declare module 'mcs-lite-ui/lib/Breadcrumb/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Breadcrumb/index'>;
}
declare module 'mcs-lite-ui/lib/Button/Button.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Button/Button'>;
}
declare module 'mcs-lite-ui/lib/Button/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Button/index'>;
}
declare module 'mcs-lite-ui/lib/Button/propMappers.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Button/propMappers'>;
}
declare module 'mcs-lite-ui/lib/Card/Card.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Card/Card'>;
}
declare module 'mcs-lite-ui/lib/Card/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Card/index'>;
}
declare module 'mcs-lite-ui/lib/Checkbox/Checkbox.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Checkbox/Checkbox'>;
}
declare module 'mcs-lite-ui/lib/Checkbox/IconCheck.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Checkbox/IconCheck'>;
}
declare module 'mcs-lite-ui/lib/Checkbox/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Checkbox/index'>;
}
declare module 'mcs-lite-ui/lib/Checkbox/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Checkbox/styled-components'>;
}
declare module 'mcs-lite-ui/lib/Code/Code.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Code/Code'>;
}
declare module 'mcs-lite-ui/lib/Code/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Code/index'>;
}
declare module 'mcs-lite-ui/lib/CopyButton/CopyButton.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/CopyButton/CopyButton'>;
}
declare module 'mcs-lite-ui/lib/CopyButton/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/CopyButton/index'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/ButtonClear.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/ButtonClear'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/ControlNumber.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/ControlNumber'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/ControlPeriod.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/ControlPeriod'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/ControlRange.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/ControlRange'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/ControlString.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/ControlString'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/ControlSwitch.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/ControlSwitch'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/DisplayMultipleValue.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/DisplayMultipleValue'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/DisplayStatus.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/DisplayStatus'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/DisplayString.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/DisplayString'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/DisplayUnitValue.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/DisplayUnitValue'>;
}
declare module 'mcs-lite-ui/lib/DataChannel/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannel/index'>;
}
declare module 'mcs-lite-ui/lib/DataChannelAdapter/API.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannelAdapter/API'>;
}
declare module 'mcs-lite-ui/lib/DataChannelAdapter/DataChannelAdapter.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannelAdapter/DataChannelAdapter'>;
}
declare module 'mcs-lite-ui/lib/DataChannelAdapter/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannelAdapter/index'>;
}
declare module 'mcs-lite-ui/lib/DataChannelCard/DataChannelCard.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannelCard/DataChannelCard'>;
}
declare module 'mcs-lite-ui/lib/DataChannelCard/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataChannelCard/index'>;
}
declare module 'mcs-lite-ui/lib/DataPointAreaChart/DataPointAreaChart.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataPointAreaChart/DataPointAreaChart'>;
}
declare module 'mcs-lite-ui/lib/DataPointAreaChart/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataPointAreaChart/index'>;
}
declare module 'mcs-lite-ui/lib/DataPointAreaChart/RechartTooltip.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DataPointAreaChart/RechartTooltip'>;
}
declare module 'mcs-lite-ui/lib/DatetimePicker/DATE_API.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DatetimePicker/DATE_API'>;
}
declare module 'mcs-lite-ui/lib/DatetimePicker/DatetimePicker.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DatetimePicker/DatetimePicker'>;
}
declare module 'mcs-lite-ui/lib/DatetimePicker/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DatetimePicker/index'>;
}
declare module 'mcs-lite-ui/lib/DatetimePicker/utils.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DatetimePicker/utils'>;
}
declare module 'mcs-lite-ui/lib/DatetimePickerDialog/DatetimePickerDialog.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DatetimePickerDialog/DatetimePickerDialog'>;
}
declare module 'mcs-lite-ui/lib/DatetimePickerDialog/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DatetimePickerDialog/index'>;
}
declare module 'mcs-lite-ui/lib/Dialog/CommonDialog.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Dialog/CommonDialog'>;
}
declare module 'mcs-lite-ui/lib/Dialog/Dialog.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Dialog/Dialog'>;
}
declare module 'mcs-lite-ui/lib/Dialog/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Dialog/index'>;
}
declare module 'mcs-lite-ui/lib/DropdownMenu/DropdownMenu.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DropdownMenu/DropdownMenu'>;
}
declare module 'mcs-lite-ui/lib/DropdownMenu/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DropdownMenu/index'>;
}
declare module 'mcs-lite-ui/lib/DropdownMenu/position.config.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DropdownMenu/position.config'>;
}
declare module 'mcs-lite-ui/lib/DropdownMenu/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/DropdownMenu/styled-components'>;
}
declare module 'mcs-lite-ui/lib/Form/ErrorMessage.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Form/ErrorMessage'>;
}
declare module 'mcs-lite-ui/lib/Form/Fieldset.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Form/Fieldset'>;
}
declare module 'mcs-lite-ui/lib/Form/Form.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Form/Form'>;
}
declare module 'mcs-lite-ui/lib/Form/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Form/index'>;
}
declare module 'mcs-lite-ui/lib/Form/ResponsivePanel.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Form/ResponsivePanel'>;
}
declare module 'mcs-lite-ui/lib/FormGroup/FormGroup.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/FormGroup/FormGroup'>;
}
declare module 'mcs-lite-ui/lib/FormGroup/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/FormGroup/index'>;
}
declare module 'mcs-lite-ui/lib/Heading/Heading.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Heading/Heading'>;
}
declare module 'mcs-lite-ui/lib/Heading/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Heading/index'>;
}
declare module 'mcs-lite-ui/lib/Hr/Hr.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Hr/Hr'>;
}
declare module 'mcs-lite-ui/lib/Hr/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Hr/index'>;
}
declare module 'mcs-lite-ui/lib/IconWarning/IconWarning.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/IconWarning/IconWarning'>;
}
declare module 'mcs-lite-ui/lib/IconWarning/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/IconWarning/index'>;
}
declare module 'mcs-lite-ui/lib/ImageDropzone/Container.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/ImageDropzone/Container'>;
}
declare module 'mcs-lite-ui/lib/ImageDropzone/Image.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/ImageDropzone/Image'>;
}
declare module 'mcs-lite-ui/lib/ImageDropzone/ImageDropzone.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/ImageDropzone/ImageDropzone'>;
}
declare module 'mcs-lite-ui/lib/ImageDropzone/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/ImageDropzone/index'>;
}
declare module 'mcs-lite-ui/lib/ImageDropzone/LoadingWrapper.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/ImageDropzone/LoadingWrapper'>;
}
declare module 'mcs-lite-ui/lib/Img/Img.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Img/Img'>;
}
declare module 'mcs-lite-ui/lib/Img/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Img/index'>;
}
declare module 'mcs-lite-ui/lib/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/index'>;
}
declare module 'mcs-lite-ui/lib/Input/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Input/index'>;
}
declare module 'mcs-lite-ui/lib/Input/Input.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Input/Input'>;
}
declare module 'mcs-lite-ui/lib/InputCheckbox/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputCheckbox/index'>;
}
declare module 'mcs-lite-ui/lib/InputCheckbox/InputCheckbox.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputCheckbox/InputCheckbox'>;
}
declare module 'mcs-lite-ui/lib/InputCheckbox/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputCheckbox/styled-components'>;
}
declare module 'mcs-lite-ui/lib/InputGroup/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputGroup/index'>;
}
declare module 'mcs-lite-ui/lib/InputGroup/InputGroup.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputGroup/InputGroup'>;
}
declare module 'mcs-lite-ui/lib/InputMultiSelect/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputMultiSelect/index'>;
}
declare module 'mcs-lite-ui/lib/InputMultiSelect/InputMultiSelect.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputMultiSelect/InputMultiSelect'>;
}
declare module 'mcs-lite-ui/lib/InputOrder/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputOrder/index'>;
}
declare module 'mcs-lite-ui/lib/InputOrder/InputOrder.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputOrder/InputOrder'>;
}
declare module 'mcs-lite-ui/lib/InputOrder/Item.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputOrder/Item'>;
}
declare module 'mcs-lite-ui/lib/InputOrder/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputOrder/styled-components'>;
}
declare module 'mcs-lite-ui/lib/InputOrder/type.flow.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputOrder/type.flow'>;
}
declare module 'mcs-lite-ui/lib/InputRadio/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputRadio/index'>;
}
declare module 'mcs-lite-ui/lib/InputRadio/InputRadio.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputRadio/InputRadio'>;
}
declare module 'mcs-lite-ui/lib/InputRadio/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputRadio/styled-components'>;
}
declare module 'mcs-lite-ui/lib/InputRange/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputRange/index'>;
}
declare module 'mcs-lite-ui/lib/InputRange/InputRange.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputRange/InputRange'>;
}
declare module 'mcs-lite-ui/lib/InputSelect/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputSelect/index'>;
}
declare module 'mcs-lite-ui/lib/InputSelect/InputSelect.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputSelect/InputSelect'>;
}
declare module 'mcs-lite-ui/lib/InputSelect/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputSelect/styled-components'>;
}
declare module 'mcs-lite-ui/lib/InputSelect/type.flow.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputSelect/type.flow'>;
}
declare module 'mcs-lite-ui/lib/InputSelect/utils.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/InputSelect/utils'>;
}
declare module 'mcs-lite-ui/lib/Label/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Label/index'>;
}
declare module 'mcs-lite-ui/lib/Label/Label.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Label/Label'>;
}
declare module 'mcs-lite-ui/lib/LandingHeader/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LandingHeader/index'>;
}
declare module 'mcs-lite-ui/lib/LandingHeader/LandingHeader.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LandingHeader/LandingHeader'>;
}
declare module 'mcs-lite-ui/lib/LandingHeader/Nav.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LandingHeader/Nav'>;
}
declare module 'mcs-lite-ui/lib/LandingHeader/NavItem.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LandingHeader/NavItem'>;
}
declare module 'mcs-lite-ui/lib/LandingHeader/NavItemBurger.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LandingHeader/NavItemBurger'>;
}
declare module 'mcs-lite-ui/lib/LandingHeader/NavItemDropdown.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LandingHeader/NavItemDropdown'>;
}
declare module 'mcs-lite-ui/lib/LazyloadOnce/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LazyloadOnce/index'>;
}
declare module 'mcs-lite-ui/lib/LazyloadOnce/LazyloadOnce.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/LazyloadOnce/LazyloadOnce'>;
}
declare module 'mcs-lite-ui/lib/Logo/MCS.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Logo/MCS'>;
}
declare module 'mcs-lite-ui/lib/Menu/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Menu/index'>;
}
declare module 'mcs-lite-ui/lib/Menu/Menu.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Menu/Menu'>;
}
declare module 'mcs-lite-ui/lib/Menu/MenuItem.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Menu/MenuItem'>;
}
declare module 'mcs-lite-ui/lib/MobileContentWrapper/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileContentWrapper/index'>;
}
declare module 'mcs-lite-ui/lib/MobileContentWrapper/MobileContentWrapper.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileContentWrapper/MobileContentWrapper'>;
}
declare module 'mcs-lite-ui/lib/MobileDeviceCard/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileDeviceCard/index'>;
}
declare module 'mcs-lite-ui/lib/MobileDeviceCard/MobileDeviceCard.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileDeviceCard/MobileDeviceCard'>;
}
declare module 'mcs-lite-ui/lib/MobileFixedFooter/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileFixedFooter/index'>;
}
declare module 'mcs-lite-ui/lib/MobileFixedFooter/MobileFixedFooter.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileFixedFooter/MobileFixedFooter'>;
}
declare module 'mcs-lite-ui/lib/MobileHeader/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileHeader/index'>;
}
declare module 'mcs-lite-ui/lib/MobileHeader/MobileHeader.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileHeader/MobileHeader'>;
}
declare module 'mcs-lite-ui/lib/MobileHeader/MobileHeaderIcon.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MobileHeader/MobileHeaderIcon'>;
}
declare module 'mcs-lite-ui/lib/MorphReplace/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MorphReplace/index'>;
}
declare module 'mcs-lite-ui/lib/MorphReplace/MorphReplace.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/MorphReplace/MorphReplace'>;
}
declare module 'mcs-lite-ui/lib/Notification/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Notification/index'>;
}
declare module 'mcs-lite-ui/lib/Notification/Notification.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Notification/Notification'>;
}
declare module 'mcs-lite-ui/lib/Orderbox/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Orderbox/index'>;
}
declare module 'mcs-lite-ui/lib/Orderbox/Orderbox.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Orderbox/Orderbox'>;
}
declare module 'mcs-lite-ui/lib/Overlay/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Overlay/index'>;
}
declare module 'mcs-lite-ui/lib/Overlay/Overlay.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Overlay/Overlay'>;
}
declare module 'mcs-lite-ui/lib/P/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/P/index'>;
}
declare module 'mcs-lite-ui/lib/P/P.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/P/P'>;
}
declare module 'mcs-lite-ui/lib/Panel/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Panel/index'>;
}
declare module 'mcs-lite-ui/lib/Panel/Panel.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Panel/Panel'>;
}
declare module 'mcs-lite-ui/lib/PanelIcon/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/PanelIcon/index'>;
}
declare module 'mcs-lite-ui/lib/PanelIcon/PanelIcon.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/PanelIcon/PanelIcon'>;
}
declare module 'mcs-lite-ui/lib/Picker/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Picker/index'>;
}
declare module 'mcs-lite-ui/lib/Picker/Picker.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Picker/Picker'>;
}
declare module 'mcs-lite-ui/lib/Picker/PickerContainer.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Picker/PickerContainer'>;
}
declare module 'mcs-lite-ui/lib/Popover/Arrow.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Popover/Arrow'>;
}
declare module 'mcs-lite-ui/lib/Popover/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Popover/index'>;
}
declare module 'mcs-lite-ui/lib/Popover/Popover.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Popover/Popover'>;
}
declare module 'mcs-lite-ui/lib/Popover/position.config.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Popover/position.config'>;
}
declare module 'mcs-lite-ui/lib/PreventDrag/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/PreventDrag/index'>;
}
declare module 'mcs-lite-ui/lib/PreventDrag/PreventDrag.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/PreventDrag/PreventDrag'>;
}
declare module 'mcs-lite-ui/lib/PullToRefresh/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/PullToRefresh/index'>;
}
declare module 'mcs-lite-ui/lib/PullToRefresh/PullToRefresh.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/PullToRefresh/PullToRefresh'>;
}
declare module 'mcs-lite-ui/lib/Rotate/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Rotate/index'>;
}
declare module 'mcs-lite-ui/lib/Rotate/Rotate.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Rotate/Rotate'>;
}
declare module 'mcs-lite-ui/lib/Select/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Select/index'>;
}
declare module 'mcs-lite-ui/lib/Select/Select.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Select/Select'>;
}
declare module 'mcs-lite-ui/lib/Select/styled-components.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Select/styled-components'>;
}
declare module 'mcs-lite-ui/lib/Select/type.flow.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Select/type.flow'>;
}
declare module 'mcs-lite-ui/lib/Small/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Small/index'>;
}
declare module 'mcs-lite-ui/lib/Small/Small.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Small/Small'>;
}
declare module 'mcs-lite-ui/lib/SpaceTop/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/SpaceTop/index'>;
}
declare module 'mcs-lite-ui/lib/SpaceTop/SpaceTop.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/SpaceTop/SpaceTop'>;
}
declare module 'mcs-lite-ui/lib/Spin/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Spin/index'>;
}
declare module 'mcs-lite-ui/lib/Spin/rotate360.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Spin/rotate360'>;
}
declare module 'mcs-lite-ui/lib/Spin/Spin.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Spin/Spin'>;
}
declare module 'mcs-lite-ui/lib/StatusLight/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/StatusLight/index'>;
}
declare module 'mcs-lite-ui/lib/StatusLight/StatusLight.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/StatusLight/StatusLight'>;
}
declare module 'mcs-lite-ui/lib/Switch/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Switch/index'>;
}
declare module 'mcs-lite-ui/lib/Switch/Switch.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Switch/Switch'>;
}
declare module 'mcs-lite-ui/lib/TabItem/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/TabItem/index'>;
}
declare module 'mcs-lite-ui/lib/TabItem/TabItem.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/TabItem/TabItem'>;
}
declare module 'mcs-lite-ui/lib/Table/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Table/index'>;
}
declare module 'mcs-lite-ui/lib/Table/Table.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Table/Table'>;
}
declare module 'mcs-lite-ui/lib/Textarea/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Textarea/index'>;
}
declare module 'mcs-lite-ui/lib/Textarea/Textarea.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Textarea/Textarea'>;
}
declare module 'mcs-lite-ui/lib/TextCenter/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/TextCenter/index'>;
}
declare module 'mcs-lite-ui/lib/TextCenter/TextCenter.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/TextCenter/TextCenter'>;
}
declare module 'mcs-lite-ui/lib/Toast/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Toast/index'>;
}
declare module 'mcs-lite-ui/lib/Toast/Toast.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Toast/Toast'>;
}
declare module 'mcs-lite-ui/lib/Tooltip/Arrow.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Tooltip/Arrow'>;
}
declare module 'mcs-lite-ui/lib/Tooltip/index.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Tooltip/index'>;
}
declare module 'mcs-lite-ui/lib/Tooltip/position.config.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Tooltip/position.config'>;
}
declare module 'mcs-lite-ui/lib/Tooltip/Tooltip.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/Tooltip/Tooltip'>;
}
declare module 'mcs-lite-ui/lib/utils/cookieHelper.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/cookieHelper'>;
}
declare module 'mcs-lite-ui/lib/utils/dataChannelHelper.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/dataChannelHelper'>;
}
declare module 'mcs-lite-ui/lib/utils/emptyFunction.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/emptyFunction'>;
}
declare module 'mcs-lite-ui/lib/utils/getCurrentYear.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/getCurrentYear'>;
}
declare module 'mcs-lite-ui/lib/utils/getScrollTop.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/getScrollTop'>;
}
declare module 'mcs-lite-ui/lib/utils/isNumber.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/isNumber'>;
}
declare module 'mcs-lite-ui/lib/utils/isString.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/isString'>;
}
declare module 'mcs-lite-ui/lib/utils/localeHelper.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/localeHelper'>;
}
declare module 'mcs-lite-ui/lib/utils/localTimeFormat.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/localTimeFormat'>;
}
declare module 'mcs-lite-ui/lib/utils/osHelper.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/osHelper'>;
}
declare module 'mcs-lite-ui/lib/utils/react-hammerjs.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/react-hammerjs'>;
}
declare module 'mcs-lite-ui/lib/utils/routerHelper.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/routerHelper'>;
}
declare module 'mcs-lite-ui/lib/utils/validators.js' {
  declare module.exports: $Exports<'mcs-lite-ui/lib/utils/validators'>;
}
