// flow-typed signature: 4a5fa1073702c27800cfe41bf558a27b
// flow-typed version: <<STUB>>/react-intl-inject-hoc_v^0.2.41/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl-inject-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl-inject-hoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl-inject-hoc/lib/index' {
  declare module.exports: any;
}

declare module 'react-intl-inject-hoc/lib/withGetMessages' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl-inject-hoc/lib/index.js' {
  declare module.exports: $Exports<'react-intl-inject-hoc/lib/index'>;
}
declare module 'react-intl-inject-hoc/lib/withGetMessages.js' {
  declare module.exports: $Exports<'react-intl-inject-hoc/lib/withGetMessages'>;
}
