// flow-typed signature: 0626fbc76da91784e3b82f953fb984d9
// flow-typed version: <<STUB>>/react-image-onload_v^1.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-onload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-onload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-onload/lib/ImageOnLoad' {
  declare module.exports: any;
}

declare module 'react-image-onload/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-onload/lib/ImageOnLoad.js' {
  declare module.exports: $Exports<'react-image-onload/lib/ImageOnLoad'>;
}
declare module 'react-image-onload/lib/index.js' {
  declare module.exports: $Exports<'react-image-onload/lib/index'>;
}
