// flow-typed signature: 1b112396023e404076c25da27c986c8d
// flow-typed version: <<STUB>>/react-input-files_v^1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-files/lib/index' {
  declare module.exports: any;
}

declare module 'react-input-files/lib/InputFiles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-files/lib/index.js' {
  declare module.exports: $Exports<'react-input-files/lib/index'>;
}
declare module 'react-input-files/lib/InputFiles.js' {
  declare module.exports: $Exports<'react-input-files/lib/InputFiles'>;
}
