// flow-typed signature: ccf22b57fd89c587a06d3ce6399eedf5
// flow-typed version: <<STUB>>/react-draggable-playground_v^1.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-draggable-playground'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-draggable-playground' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-draggable-playground/lib/DraggableItem' {
  declare module.exports: any;
}

declare module 'react-draggable-playground/lib/DraggableParent' {
  declare module.exports: any;
}

declare module 'react-draggable-playground/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-draggable-playground/lib/DraggableItem.js' {
  declare module.exports: $Exports<'react-draggable-playground/lib/DraggableItem'>;
}
declare module 'react-draggable-playground/lib/DraggableParent.js' {
  declare module.exports: $Exports<'react-draggable-playground/lib/DraggableParent'>;
}
declare module 'react-draggable-playground/lib/index.js' {
  declare module.exports: $Exports<'react-draggable-playground/lib/index'>;
}
