// flow-typed signature: 873f4051ca77cf40141069aa3cca845d
// flow-typed version: <<STUB>>/socketio-wildcard_v^2.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socketio-wildcard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socketio-wildcard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socketio-wildcard/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socketio-wildcard/index' {
  declare module.exports: $Exports<'socketio-wildcard'>;
}
declare module 'socketio-wildcard/index.js' {
  declare module.exports: $Exports<'socketio-wildcard'>;
}
declare module 'socketio-wildcard/test/index.js' {
  declare module.exports: $Exports<'socketio-wildcard/test/index'>;
}
