// flow-typed signature: f16890540fd9b9e0bd8d8736fa6158b2
// flow-typed version: <<STUB>>/@pisano/enzyme-adapter-react-16_v^1.1.1-pisano.public.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pisano/enzyme-adapter-react-16'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pisano/enzyme-adapter-react-16' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pisano/enzyme-adapter-react-16/build/index' {
  declare module.exports: any;
}

declare module '@pisano/enzyme-adapter-react-16/build/ReactSixteenAdapter' {
  declare module.exports: any;
}

declare module '@pisano/enzyme-adapter-react-16/src/index' {
  declare module.exports: any;
}

declare module '@pisano/enzyme-adapter-react-16/src/ReactSixteenAdapter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pisano/enzyme-adapter-react-16/build/index.js' {
  declare module.exports: $Exports<'@pisano/enzyme-adapter-react-16/build/index'>;
}
declare module '@pisano/enzyme-adapter-react-16/build/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'@pisano/enzyme-adapter-react-16/build/ReactSixteenAdapter'>;
}
declare module '@pisano/enzyme-adapter-react-16/src/index.js' {
  declare module.exports: $Exports<'@pisano/enzyme-adapter-react-16/src/index'>;
}
declare module '@pisano/enzyme-adapter-react-16/src/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'@pisano/enzyme-adapter-react-16/src/ReactSixteenAdapter'>;
}
