// flow-typed signature: 197116d0765365964829967831cf4caa
// flow-typed version: <<STUB>>/@pisano/enzyme_v^3.3.0-pisano.public.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pisano/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pisano/enzyme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pisano/enzyme/build/configuration' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/Debug' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/EnzymeAdapter' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/index' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/mount' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/ReactWrapper' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/render' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/RSTTraversal' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/selectors' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/shallow' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/ShallowWrapper' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/Utils' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/build/validateAdapter' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/mount' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/ReactWrapper' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/render' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/shallow' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/ShallowWrapper' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/configuration' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/Debug' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/EnzymeAdapter' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/index' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/mount' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/ReactWrapper' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/render' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/RSTTraversal' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/selectors' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/shallow' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/ShallowWrapper' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/Utils' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/src/validateAdapter' {
  declare module.exports: any;
}

declare module '@pisano/enzyme/withDom' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pisano/enzyme/build/configuration.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/configuration'>;
}
declare module '@pisano/enzyme/build/Debug.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/Debug'>;
}
declare module '@pisano/enzyme/build/EnzymeAdapter.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/EnzymeAdapter'>;
}
declare module '@pisano/enzyme/build/index.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/index'>;
}
declare module '@pisano/enzyme/build/mount.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/mount'>;
}
declare module '@pisano/enzyme/build/ReactWrapper.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/ReactWrapper'>;
}
declare module '@pisano/enzyme/build/render.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/render'>;
}
declare module '@pisano/enzyme/build/RSTTraversal.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/RSTTraversal'>;
}
declare module '@pisano/enzyme/build/selectors.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/selectors'>;
}
declare module '@pisano/enzyme/build/shallow.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/shallow'>;
}
declare module '@pisano/enzyme/build/ShallowWrapper.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/ShallowWrapper'>;
}
declare module '@pisano/enzyme/build/Utils.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/Utils'>;
}
declare module '@pisano/enzyme/build/validateAdapter.js' {
  declare module.exports: $Exports<'@pisano/enzyme/build/validateAdapter'>;
}
declare module '@pisano/enzyme/mount.js' {
  declare module.exports: $Exports<'@pisano/enzyme/mount'>;
}
declare module '@pisano/enzyme/ReactWrapper.js' {
  declare module.exports: $Exports<'@pisano/enzyme/ReactWrapper'>;
}
declare module '@pisano/enzyme/render.js' {
  declare module.exports: $Exports<'@pisano/enzyme/render'>;
}
declare module '@pisano/enzyme/shallow.js' {
  declare module.exports: $Exports<'@pisano/enzyme/shallow'>;
}
declare module '@pisano/enzyme/ShallowWrapper.js' {
  declare module.exports: $Exports<'@pisano/enzyme/ShallowWrapper'>;
}
declare module '@pisano/enzyme/src/configuration.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/configuration'>;
}
declare module '@pisano/enzyme/src/Debug.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/Debug'>;
}
declare module '@pisano/enzyme/src/EnzymeAdapter.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/EnzymeAdapter'>;
}
declare module '@pisano/enzyme/src/index.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/index'>;
}
declare module '@pisano/enzyme/src/mount.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/mount'>;
}
declare module '@pisano/enzyme/src/ReactWrapper.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/ReactWrapper'>;
}
declare module '@pisano/enzyme/src/render.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/render'>;
}
declare module '@pisano/enzyme/src/RSTTraversal.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/RSTTraversal'>;
}
declare module '@pisano/enzyme/src/selectors.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/selectors'>;
}
declare module '@pisano/enzyme/src/shallow.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/shallow'>;
}
declare module '@pisano/enzyme/src/ShallowWrapper.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/ShallowWrapper'>;
}
declare module '@pisano/enzyme/src/Utils.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/Utils'>;
}
declare module '@pisano/enzyme/src/validateAdapter.js' {
  declare module.exports: $Exports<'@pisano/enzyme/src/validateAdapter'>;
}
declare module '@pisano/enzyme/withDom.js' {
  declare module.exports: $Exports<'@pisano/enzyme/withDom'>;
}
